name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libportmidi-dev

      - name: Test
        run: |
          make install test
