name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.23
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Test
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libportmidi-dev libasound2-dev
          make deps test
